In [1]:
from sklearn.preprocessing import OneHotEncoder

In [4]:
import pandas as pd
import seaborn as sns
data = sns.load_dataset('titanic')
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
data.who.value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [6]:
onehot = OneHotEncoder()
ans = onehot.fit_transform(data.loc[:,['who']]).toarray()

In [7]:
ans

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.]], shape=(891, 3))

In [8]:
new_features = onehot.get_feature_names_out()
new_features

array(['who_child', 'who_man', 'who_woman'], dtype=object)

In [9]:
data.loc[:,new_features] = ans

In [11]:
data.head(20)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,who_child,who_man,who_woman
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.0,1.0,0.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0.0,0.0,1.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0.0,0.0,1.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0.0,0.0,1.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.0,1.0,0.0
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True,0.0,1.0,0.0
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True,0.0,1.0,0.0
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False,1.0,0.0,0.0
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False,0.0,0.0,1.0
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False,1.0,0.0,0.0
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False,1.0,0.0,0.0
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,0.0,0.0,1.0
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.0,1.0,0.0
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False,0.0,1.0,0.0
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True,1.0,0.0,0.0
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True,0.0,0.0,1.0
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False,1.0,0.0,0.0
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True,0.0,1.0,0.0
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False,0.0,0.0,1.0
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True,0.0,0.0,1.0

In [12]:
# Map
data.loc[:,'class'].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64

In [13]:
data.loc[:,'class_num'] = data.loc[:,'class'].map({'First':1,'Second':2,'Third':3})
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,who_child,who_man,who_woman,class_num
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.0,1.0,0.0,3
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0.0,0.0,1.0,1
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0.0,0.0,1.0,3
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0.0,0.0,1.0,1
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.0,1.0,0.0,3

In [14]:
# get dummies
pd.get_dummies(data.who,dtype='int')

     child  man  woman
0        0    1      0
1        0    0      1
2        0    0      1
3        0    0      1
4        0    1      0
..     ...  ...    ...
886      0    1      0
887      0    0      1
888      0    0      1
889      0    1      0
890      0    1      0

[891 rows x 3 columns]

In [15]:
import joblib
joblib.dump(onehot,'encoder.pkl')

['encoder.pkl']